mod auth_key;
mod message;
mod msg;
mod msg_id;
mod pack;
mod seq_no;
mod unpack;

pub use auth_key::{AuthKey, AuthKeyAuxHash, AuthKeyId, MsgKey};
pub use message::{ExternalHeader, InternalHeader, PlainMsgHeader};
pub use msg::Msg;
pub use msg_id::{MsgId, MsgIds, msg_id, is_msg_id_valid};
pub use pack::{pack_encrypted, pack_plain};
pub use seq_no::{SeqNo, SeqNos};
pub use unpack::{MessageLengthCheckError, MsgIdCheckError, MsgKeyCheckError, auth_key_id};

pub const MAX_ENCRYPTED_PADDING: usize = 1024;

pub type PlainHeader = unbite::Raw<{ PlainMsgHeader::LEN }>;

pub type EncryptedHeader =
    unbite::Raw<{ ExternalHeader::LEN + InternalHeader::LEN + Msg::HEADER_LEN }>;

pub type EncryptedPadding = unbite::Raw<MAX_ENCRYPTED_PADDING>;

/// # Session
///
/// A (random) 64-bit number generated by the client to distinguish
/// between individual sessions (for example, between different
/// instances of the application, created with the same authorization key).
/// The session in conjunction with the key identifier corresponds
/// to an application instance. The server can maintain session state.
/// Under no circumstances can a message meant for one session be sent
/// into a different session. The server may unilaterally forget any
/// client sessions; clients should be able to handle this.
///
/// ---
///
/// <https://core.telegram.org/mtproto/description#session>
pub type Session = i64;

/// # Server Salt
///
/// A (random) 64-bit number changed every 30 minutes (separately
/// for each session) at the request of the server. All subsequent
/// messages must contain the new salt (although, messages with
/// the old salt are still accepted for a further 1800 seconds).
/// Required to protect against replay attacks and certain tricks associated
/// with adjusting the client clock to a moment in the distant future.
///
/// ---
///
/// <https://core.telegram.org/mtproto/description#server-salt>
pub type Salt = i64;

/// For MTProto 2.0, the algorithm for computing
/// aes_key and aes_iv from auth_key and msg_key is
/// <...> where x = 0 for messages from client to
/// server and x = 8 for those from server to client.
///
/// ---
///
/// <https://core.telegram.org/mtproto/description#defining-aes-key-and-initialization-vector>
#[must_use]
#[repr(usize)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Side {
    Client = 0,
    Server = 8,
}

impl Side {
    #[must_use]
    #[inline(always)]
    pub const fn x(self) -> usize {
        self as usize
    }
}
