mod auth_key;
mod message;
mod msg;
mod msg_id;
mod pack;
mod seq_no;
mod unpack;

use std::ops::RangeInclusive;

pub use auth_key::{AuthKey, AuthKeyAuxHash, AuthKeyId, MsgKey};
pub use message::{ExternalHeader, InternalHeader, UnencryptedMessage};
pub use msg::{BufMsg, BufMsgError, Message, Msg, RpcResult, NegativeBytesError};
pub use msg_id::{ClientMsgIds, MsgId, MsgIdError, ServerMsgIds, msg_id};
pub use pack::{EncryptedEnvelope, pack_plain};
pub use seq_no::{SeqNo, SeqNoError, SeqNos, content_related};
pub use unpack::{
    AuthKeyIdError, MessageLengthCheckError, MsgIdCheckError, MsgKeyCheckError, SessionIdError,
    unpack_auth_key_id,
};

pub const ENCRYPTED_PADDING_RANGE: RangeInclusive<usize> = 12..=1024;

pub type PlainHeader = unbite::Raw<{ UnencryptedMessage::LEN }>;

/// # Session
///
/// A (random) 64-bit number generated by the client to distinguish
/// between individual sessions (for example, between different
/// instances of the application, created with the same authorization key).
/// The session in conjunction with the key identifier corresponds
/// to an application instance. The server can maintain session state.
/// Under no circumstances can a message meant for one session be sent
/// into a different session. The server may unilaterally forget any
/// client sessions; clients should be able to handle this.
///
/// ---
///
/// <https://core.telegram.org/mtproto/description#session>
pub type Session = i64;

/// # Server Salt
///
/// A (random) 64-bit number changed every 30 minutes (separately
/// for each session) at the request of the server. All subsequent
/// messages must contain the new salt (although, messages with
/// the old salt are still accepted for a further 1800 seconds).
/// Required to protect against replay attacks and certain tricks associated
/// with adjusting the client clock to a moment in the distant future.
///
/// ---
///
/// <https://core.telegram.org/mtproto/description#server-salt>
pub type Salt = i64;

/// For MTProto 2.0, the algorithm for computing
/// aes_key and aes_iv from auth_key and msg_key is
/// <...> where x = 0 for messages from client to
/// server and x = 8 for those from server to client.
///
/// ---
///
/// <https://core.telegram.org/mtproto/description#defining-aes-key-and-initialization-vector>
#[must_use]
#[repr(usize)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Side {
    Client = 0,
    Server = 8,
}

impl Side {
    #[must_use]
    #[inline(always)]
    pub const fn x(self) -> usize {
        self as usize
    }
}
