use std::fmt::{Debug, Display, Formatter, Result};
use std::time::{SystemTime, UNIX_EPOCH};

/// # Message Identifier (msg_id)
///
/// A (time-dependent) 64-bit number used uniquely to identify a
/// message within a session. Client message identifiers are divisible
/// by 4, server message identifiers modulo 4 yield 1 if the message
/// is a response to a client message, and 3 otherwise. Client message
/// identifiers must increase monotonically (within a single session),
/// the same as server message identifiers, and must approximately equal
/// unixtime*2^32. This way, a message identifier points to the approximate
/// moment in time the message was created. A message is rejected over
/// 300 seconds after it is created or 30 seconds before it is created
/// (this is needed to protect from replay attacks). In this situation,
/// it must be re-sent with a different identifier (or placed in a
/// container with a higher identifier). The identifier of a message
/// container must be strictly greater than those of its nested messages.
///
/// **Important:** to counter replay-attacks the lower 32 bits of
/// **msg_id** passed by the client must not be empty and must present
/// a fractional part of the time point when the message was created.
///
/// ---
///
/// https://core.telegram.org/mtproto/description#message-identifier-msg-id
pub type MsgId = i64;

/// Calculates a new [`MsgId`] from given `unix_time`.
///
/// # Panics
///
/// * If the [`SystemTime`] is before [`UNIX_EPOCH`].
#[inline]
#[must_use]
pub fn msg_id(unix_time: SystemTime) -> MsgId {
    let unix_time = unix_time
        .duration_since(UNIX_EPOCH)
        .expect("system clock time to be after the Unix epoch");

    let secs = unix_time.as_secs() as i64;
    let subsec_nanos = unix_time.subsec_nanos() as i64;

    secs << 32 | subsec_nanos << 2
}

/// [`MsgId`] counter for a single connection.
#[must_use]
pub struct MsgIds {
    last: MsgId,
}

impl Debug for MsgIds {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        f.debug_struct("MsgIds")
            .field("last", &format_args!("{:#018x}", self.last))
            .finish()
    }
}

impl Display for MsgIds {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        write!(f, "msg ids [last={}]", self.last)
    }
}

impl MsgIds {
    /// Creates a new counter starting with `unix_time`.
    ///
    /// # Panics
    ///
    /// * If the [`SystemTime`] is before [`UNIX_EPOCH`].
    #[inline]
    pub fn new(unix_time: SystemTime) -> Self {
        Self {
            last: msg_id(unix_time),
        }
    }

    /// Returns the last [`MsgId`] generated by this counter.
    #[inline]
    #[must_use]
    pub fn last(&self) -> MsgId {
        self.last
    }

    /// Calculates next [`MsgId`] for given [`SystemTime`].
    ///
    /// # Panics
    ///
    /// * If the [`SystemTime`] is before [`UNIX_EPOCH`].
    #[inline]
    #[must_use]
    pub fn get(&mut self, unix_time: SystemTime) -> MsgId {
        let msg_id = msg_id(unix_time);

        if self.last >= msg_id {
            self.last += 4;

            self.last
        } else {
            self.last = msg_id;

            msg_id
        }
    }
}
