use std::fmt::{Debug, Display, Formatter};
use std::time::SystemTime;

use crate::mtproto::{MsgId, msg_id};

/// [`MsgId`] counter for a single connection.
#[must_use]
pub struct ClientMsgIds {
    last: MsgId,
}

impl Debug for ClientMsgIds {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ClientMsgIds")
            .field("last", &format_args!("{:#018x}", self.last))
            .finish()
    }
}

impl Display for ClientMsgIds {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "client msg ids [last={}]", self.last)
    }
}

impl ClientMsgIds {
    /// Creates a new counter starting with `unix_time`.
    ///
    /// # Panics
    ///
    /// * If the [`SystemTime`] is before [`UNIX_EPOCH`].
    ///
    /// [`UNIX_EPOCH`]: std::time::UNIX_EPOCH
    #[inline]
    pub fn new(unix_time: SystemTime) -> Self {
        Self {
            last: msg_id(unix_time),
        }
    }

    /// Returns the last [`MsgId`] generated by this counter.
    #[inline]
    #[must_use]
    pub const fn last(&self) -> MsgId {
        self.last
    }

    /// Calculates next [`MsgId`] for given [`SystemTime`].
    ///
    /// # Panics
    ///
    /// * If the [`SystemTime`] is before [`UNIX_EPOCH`].
    #[inline]
    #[must_use]
    pub fn get(&mut self, unix_time: SystemTime) -> MsgId {
        let msg_id = msg_id(unix_time);

        if self.last >= msg_id {
            self.last += 4;

            self.last
        } else {
            self.last = msg_id;

            msg_id
        }
    }
}
